# Generated by Django 4.1.5 on 2023-01-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct', models.CharField(max_length=255)),
                ('week', models.CharField(blank=True, default=1, max_length=11)),
                ('affiliate', models.CharField(max_length=255)),
                ('pid', models.CharField(max_length=255)),
                ('install_partner', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('sales_rep_name', models.CharField(max_length=255)),
                ('kw', models.FloatField(default=0.0)),
                ('inactive_date', models.DateTimeField(auto_now_add=True)),
                ('cancel', models.FloatField(blank=True, default=1, null=True)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('m1_date', models.DateTimeField(auto_now_add=True)),
                ('m2_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('gross_account_value', models.FloatField(default=0.0)),
                ('epc', models.FloatField()),
                ('net_epc', models.FloatField()),
                ('dealer_fee_percentage', models.FloatField()),
                ('dealer_fee_dollar', models.FloatField()),
                ('shows', models.FloatField()),
                ('redline', models.FloatField()),
                ('total_for_acct', models.FloatField()),
                ('prev_paid', models.FloatField()),
                ('last_date_pd', models.DateTimeField(auto_now_add=True)),
                ('m1_this_week', models.FloatField()),
                ('install_m2_this_week', models.FloatField()),
                ('prev_deducted', models.FloatField()),
                ('cancel_fee', models.FloatField()),
                ('cancel_deduction', models.CharField(max_length=11)),
                ('lead_cost', models.FloatField(blank=True, default=1, null=True)),
                ('ad_pay_back', models.FloatField()),
                ('total_in_period', models.FloatField()),
            ],
        ),
    ]
